////////////////////////////////////////////////////////////////////////////////
/////////////////////////*TANIMLAMALAR*/////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
#define DIO1                          RB3_BIT
#define DIO1_dir                      TRISB3_BIT
#define DIO2                          RB15_BIT
#define DIO2_dir                      TRISB15_BIT
#define DIO3                          RB6_BIT
#define DIO3_dir                      TRISB6_BIT
#define DIO4                          RB7_BIT
#define DIO4_dir                      TRISB7_BIT
#define DIO5                          RB8_BIT
#define DIO5_dir                      TRISB8_BIT
#define DIO6                          RB9_BIT
#define DIO6_dir                      TRISB9_BIT
#define DIO7                          RB10_BIT
#define DIO7_dir                      TRISB10_BIT
#define DIO10                         RB4_BIT
#define DIO10_dir                     TRISB4_BIT
#define DIO11                         RB2_BIT
#define DIO11_dir                     TRISB2_BIT
#define DIO12                         RB11_BIT
#define DIO12_dir                     TRISB11_BIT
#define DIO13                         RB12_BIT
#define DIO13_dir                     TRISB12_BIT
#define DIO14                         RB13_BIT
#define DIO14_dir                     TRISB13_BIT
#define DIO15                         RB14_BIT
#define DIO15_dir                     TRISB14_BIT
#define DIO16                         RF4_BIT
#define DIO16_dir                     TRISF4_BIT
#define DIO17                         RF5_BIT
#define DIO17_dir                     TRISF5_BIT
#define DIO18                         RF3_BIT
#define DIO18_dir                     TRISF3_BIT
#define DIO20                         RD1_BIT
#define DIO20_dir                     TRISD1_BIT
#define DIO21                         RD2_BIT
#define DIO21_dir                     TRISD2_BIT
#define DIO22                         RD3_BIT
#define DIO22_dir                     TRISD3_BIT
#define DIO23                         RD4_BIT
#define DIO23_dir                     TRISD4_BIT
#define DIO24                         RD5_BIT
#define DIO24_dir                     TRISD5_BIT
#define DIO25                         RE0_BIT
#define DIO25_dir                     TRISE0_BIT
#define DIO26                         RE1_BIT
#define DIO26_dir                     TRISE1_BIT
#define DIO27                         RE2_BIT
#define DIO27_dir                     TRISE2_BIT
#define DIO28                         RE3_BIT
#define DIO28_dir                     TRISE3_BIT
#define DIO29                         RE4_BIT
#define DIO29_dir                     TRISE4_BIT
#define DIO32                         RE5_BIT
#define DIO32_dir                     TRISE5_BIT
#define DIO33                         RE6_BIT
#define DIO33_dir                     TRISE6_BIT
#define DIO34                         RE7_BIT
#define DIO34_dir                     TRISE7_BIT
#define DIO35                         RG6_BIT
#define DIO35_dir                     TRISG6_BIT
